# Generated by Django 3.2 on 2021-05-25 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClasseDePerigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='LocalArmazenamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='SimboloGHS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='SubClassesDePerigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=500, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('sinonimo', models.CharField(max_length=100, verbose_name='Sinonimo')),
                ('incompatibilidade', models.CharField(max_length=100, verbose_name='Incompatibilidade')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('lote', models.CharField(max_length=100, verbose_name='Lote')),
                ('validate', models.DateTimeField(verbose_name='Data de Validade')),
                ('link_FISPQ', models.CharField(max_length=100, verbose_name='link FISPQ')),
                ('residuo', models.CharField(max_length=100, verbose_name='Residuo')),
                ('classe_de_perigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.classedeperigo')),
                ('local_armazenamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.localarmazenamento')),
                ('simbolo_ghs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.simbologhs')),
                ('sub_classe_de_perigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subclassesdeperigo')),
            ],
        ),
    ]
